# go语言defer和recover的使用

- [go语言defer和recover的使用](#go语言defer和recover的使用)
  - [1. 说明](#1-说明)
    - [1.1 defer 的应用场景](#11-defer-的应用场景)
    - [1.2 defer 的特点](#12-defer-的特点)
    - [1.3 recover 的特点](#13-recover-的特点)
    - [1.4 panic 的特点](#14-panic-的特点)
  - [2. 测试示例](#2-测试示例)
    - [2.1 defer 的执行顺序: 先进后出](#21-defer-的执行顺序-先进后出)
    - [2.2 defer 参数预计算](#22-defer-参数预计算)
    - [2.3 defer 函数执行在 return 之后 (可修改返回指针的内容)](#23-defer-函数执行在-return-之后-可修改返回指针的内容)
    - [2.4 defer 异常捕获](#24-defer-异常捕获)
    - [2.5 defer 资源关闭](#25-defer-资源关闭)

## 1. 说明

### 1.1 defer 的应用场景

1. 资源释放
   1. 文件打开资源
   2. 网络连接关闭
2. 异常捕获和处理
3. 参数的预计算

### 1.2 defer 的特点

1. defer 关键词用来声明一个延迟调用函数，该函数可以是匿名函数也可以是具名函数
2. defer 延迟函数执行时间(位置): 方法return之后，返回参数到调用方法之前
3. defer 延迟函数可以在方法返回之后改变函数的返回值(改变指针有效)
4. 在方法结束(正常返回，异常结束)都会去调用 defer 声明的延迟函数，可以有效避免因异常导致的资源无法释放的问题
5. 可以指定多个defer 延迟函数，多个延时函数执行顺序为后进先出
6. defer 通常用于资源释放、异常捕获等场景，例如:关闭连接，关闭文件等
7. defer 与 recover 配合可以实现异常捕获与处理逻辑
8. 不建议在 for 循环中使用 defer

### 1.3 recover 的特点

1. go 语言的内建函数，可以让进入宕机流程中的 goroutine 恢复过来
2. recover 仅在延迟函数 defer 中有效，在正常的执行过程中，调用 recover 会返回 nil 并且没有其他任何效果
3. 如果当前的 goroutine 出现 panic，调用 recover 可以捕获到 panic 的输入值，并且恢复正常的执行

### 1.4 panic 的特点

1. go语言的一种异常机制
2. 可通过panic 函数主动抛出异常


## 2. 测试示例

### 2.1 defer 的执行顺序: 先进后出

- demo

```go

// 具名函数
func f1() {
	fmt.Println("具名函数")
}

// defer 的顺序
// defer 关键字用来声明一个延迟调用函数
// 该函数可以时匿名函数或具名函数
// defer 延迟函数的执行顺序位后进先出
func DeferCase() {
	fmt.Println("开始执行")
	defer func() {
		fmt.Println("匿名函数1")
	}()
	defer f1()
	defer func() {
		fmt.Println("匿名函数2")
	}()
	fmt.Println("结束执行")
}
```

- output

```text
开始执行
结束执行
匿名函数2
具名函数
匿名函数1
```

### 2.2 defer 参数预计算

- demo

```go
func DeferCase() {
	i := 1
	defer func() {
		fmt.Println("无参数,这里打印值为主函数结束后的值", i)
	}()

	defer func(j int) {
		fmt.Println("带参数,这里传递代码段位置所在的值", j)
	}(i)

	i = 100
}
```

- output

```text
带参数,这里传递代码段位置所在的值 1
无参数,这里打印值为主函数结束后的值 100
```

### 2.3 defer 函数执行在 return 之后 (可修改返回指针的内容)

- demo

```go
var g = 100

func f2() (int, *int) {
	defer func() {
		g = 200
	}()
	fmt.Println("f2 g:", g)
	return g, &g // defer 在 return 之后执行, defer 只能修改指针的值
}

// defer 函数执行在 return 之后
func DeferCase() {
	i, j := f2()
	fmt.Printf("i: %d; j: %d, g: %d", i, *j, g) // 100, 200, 200
}
```

- output

```text
f2 g: 100
i: 100; j: 200, g: 200====== defer + recover 函数执行在 return 之后
```

### 2.4 defer 异常捕获

- demo

```go
func ExceptionCase() {
	defer func() {
		err := recover() // recover 捕获 panic
		if err != nil {
			fmt.Printf("异常处理: %#v\n", err)
		}
	}()
	fmt.Println("开始执行 ExceptionCase 方法")
	panic("panic : 抛出异常") 
	// 函数内 panic 之后的代码不执行
	fmt.Println("结束执行 ExceptionCase 方法")
}
```

- output

```text
开始执行 ExceptionCase 方法
异常处理: "panic : 抛出异常"
```

### 2.5 defer 资源关闭

```go
// defer 资源关闭
func FileReadCase() {
	file, err := os.Open("readme.md")
	if err != nil {
		log.Fatalf("Open error: %#v", err)
	}
	// 通过 defer 条用资源释放的方法
	// defer file.Close()
	defer func() {
		file.Close()
		fmt.Println("释放文件资源完成")
	}()
	buf := make([]byte, 1024)
	for {
		n, err := file.Read(buf)
		if err != nil && err != io.EOF {
			log.Fatalf("Read error: %#v", err)
		}
		if n == 0 { // 读取完毕
			break
		}
		fmt.Print(string(buf[:n]))
	}
}
```
